### ISSUE TITLE
Everyone: Learn about binary videos & take notes

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/flask_portfolio#11]
We all took notes on the collegeboard videos, and here are our individual notes linked

[Justin](https://docs.google.com/document/d/1-CbXjcedDSxMuHECOvv7dvF_tcjbSF0LtGk_NMxmy2w/edit?usp=sharing)
[Tianbin](https://docs.google.com/document/d/1eOz0QMawSIe8ViSo3b6fR6LdZRAmMDKshRM_cRA0Ch4/edit?usp=sharing)
[Stanley](https://docs.google.com/document/d/1iLSGaSGQ2lFVq5InfgJbE6u6p0w_IpodkqXK8_BVClI/edit?usp=sharing)
[Yolanda](https://docs.google.com/document/d/10EvycQrFUT_EgIYDN1qOvUQcC0J9ivYZeZfBbqQlH-o/edit?usp=sharing)

**Comment by TianbinLiu** [comment]
I update my notes

**Comment by yolandayangg** [comment]
Finished 2.1 daily videos and notes in class.
