### ISSUE TITLE
Wire Framing

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/flask_portfolio#2]
make wire frame for website. consists of different tabs (questions/answers, discussions, find a group, etc.)

Google doc: https://docs.google.com/document/d/117YVkBIJcQRaG9IsARubCS8t9pKdKBII1ujNwGlKgfk/edit?usp=sharing

**Comment by yolandayangg** [comment]
This includes the ideas that we thought of for our website. We plan on creating a space for people to read and review books from fellow nighthawks

**Comment by jm1021** [comment]
Look at this I see some good ideas for a book site.  Also, the home page looks good.  It seems like you could make some home page progress next week with this kind of an outline.
