### ISSUE TITLE
Justin- attend tutorial with Mr. M and prepare some questions about ASCII; how to add elements like ASCII character into the Binary Math display

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/flask_portfolio#31]

**Comment by yolandayangg** [comment]
Make sure to also to let us know what you learned and how to do it.

**Comment by TheRadRabbidRabbit** [comment]
I didn't have much time to talk about ASCII because I had to talk to him about other things as well, but this is what we talked about https://docs.google.com/document/d/1w3EPi1tSR8iRFmAFliB4Lp_e6SdC04jf8oUsjTIBLvY/edit?usp=sharing
