### ISSUE TITLE
RGB Values with an Image, Frontend, grayscaling

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/flask_portfolio#38]
button to grayscale image
![image](https://user-images.githubusercontent.com/89219476/135900607-706e77cc-1cb0-479b-ad09-1013c998ca48.png)

**Comment by Stanleyy03840** [comment]
button to greyscale image 
![image](https://user-images.githubusercontent.com/89219476/135900493-621d37a3-cd94-4c47-94f1-5a1be6185712.png)
