### ISSUE TITLE
Research/Study sheet/journal

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/flask_portfolio#40]
What is base2, base8, base16. what is base64? How is base64 different? what are some ideas from this research that you can use in your PBL project? (requirements). Make sure to put it in simple language or everyone to understand.

**Comment by TheRadRabbidRabbit** [comment]
https://docs.google.com/document/d/1KD1BIqaWoBsD48YYa9w8Wri7Nm3j-ngzZ26PQ9Mjqnw/edit?usp=sharing I hope this gives a good explanation. I tried showing how they worked with examples

**Comment by yolandayangg** [comment]
Great. Can you also add ideas of how we can use these things to our project? Also I don't think there was any description of what base2 was.
