### ISSUE TITLE
Signed Addition

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/flask_portfolio#49]
Completed by Stanley
- [x] 2 rows of bits
- [x] add pictures from assest to show bulb on/off
- [x] display solution of each row of bits
- [x] display solution of both rows

**Comment by yolandayangg** [comment]
![Screen Shot 2021-10-11 at 7 40 06 PM](https://user-images.githubusercontent.com/89219568/136882170-51cfc058-9140-40b9-99a4-ed7218b3b676.png)

**Comment by Stanleyy03840** [comment]
- [x] 2 rows of bits
- [x] add pictures from assest to show bulb on/off
- [x] display solution of each row of bits
- [x] display solution of both rows
