### ISSUE TITLE
Color Codes

### ISSUE THREAD

**Issue by yolandayangg** [yolandayangg/flask_portfolio#51]
Completed by Stanley and Tianbin

- [x] 3 rows of bits for each color (R,G,B)
- [x] decimal value for each color
- [x] hexcode and rgb values
- [x] display color

**Comment by TianbinLiu** [comment]
Add <input type="color"> to RGB html (create a color picker)
Don't know how to use 3 rows representing R, G, B

**Comment by yolandayangg** [comment]
![Screen Shot 2021-10-11 at 7 14 11 PM](https://user-images.githubusercontent.com/89219568/136879686-d747c955-ab9f-4480-bbc6-e364ef825567.png)
