### ISSUE TITLE
Brain Write for website

### ISSUE THREAD

**Issue by Stanleyy03840** [yolandayangg/flask_portfolio#8]
[Brain Write for Website](https://docs.google.com/document/d/1wBZ-OxrYTzXeohSZZVYkkjtZYrSEx0dG-DXpWUNH2AI/edit?usp=sharing)
brain write for website that we used before makign the wire frame of our website

**Comment by Stanleyy03840** [comment]
brain write for website that we did before adding the best ideas to website. we used ideas from this brain write in order to wire fram the website

**Comment by yolandayangg** [comment]
We took turns writing down our ideas and we all expanded each idea after each round.
